// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace RegistrationApplication.Models;

public partial class Solution4Africa_MainContext : DbContext
{
    //public Solution4Africa_MainContext(DbContextOptions<Solution4Africa_MainContext> options)
    //    : base(options)
    //{
    //}
    
    public Solution4Africa_MainContext()
    {
        
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(App.Configuration.GetConnectionString("DefaultConnection"));
    }
    public virtual DbSet<Trainer> Trainers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Trainer>(entity =>
        {
            entity.HasKey(e => e.TrainerId).HasName("PK__tmp_ms_x__8B0EB951D2E72295");

            entity.Property(e => e.TrainerId).HasColumnName("Trainer_Id");
            entity.Property(e => e.EducationLevel)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Education_Level");
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("First_Name");
            entity.Property(e => e.LastName)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Last_Name");
            entity.Property(e => e.ShortDescription)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Short_Description");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}