// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RegistrationApplication.Models;

public partial class TrainerPicture
{
    public int TrainerPictureId { get; set; }

    public byte[] Picture { get; set; }

    public string Description { get; set; }

    public string FileExtension { get; set; }

    public decimal? Size { get; set; }

    public int? TrainerId { get; set; }

    public virtual Trainer Trainer { get; set; }
}