// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RegistrationApplication.Models;

public partial class Trainer
{
    public int TrainerId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string ShortDescription { get; set; }

    public int? Age { get; set; }

    public string EducationLevel { get; set; }

    public byte[] Picture { get; set; }
}